version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    environment:
      - DJANGO_ALLOWED_HOSTS=*

  ngrok:
    image: ngrok/ngrok:latest
    # Команда говорит: "прокинь туннель на сервис 'web' (порт 8000)"
    command: http web:8000
    ports:
      - "4040:4040" # Это порт для панели управления ngrok
    environment:
      # Токен подтянется сам из файла .env
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - web